# Generated by Django 2.2.6 on 2019-11-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Surname')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Login')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('activity', models.CharField(max_length=50, verbose_name='Activity')),
            ],
        ),
    ]
