# Generated by Django 2.2.6 on 2019-11-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.CharField(choices=[('gym', 'Gym'), ('crossfit', 'CrossFit'), ('volleyball', 'Volleyball'), ('box', 'Boxing')], max_length=50, verbose_name='Activity'),
        ),
    ]
